// ============================================================
// SREENIVASA MULTI SPECIALITY HOSPITAL — DOCTORS & SPECIALISTS ROSTER
// Board-Listed Hospital Specialists & Medical Leadership
// ============================================================

export interface Doctor {
  slug: string;
  name: string;
  designation: string;
  roleBadge?: string;
  hospitalName?: string;
  qualifications?: string;
  speciality: string;
  specialitySlug: string;
  secondarySpecialitySlug?: string;
  experience?: string;
  opdTimings?: string;
  phone?: string;
  focusAreas: string[];
  bio: string;
  photo?: string;
  photoAlt: string;
  appointmentLabel: string;
  isVerified: boolean;
  isLeadership?: boolean;
}

export const doctors: Doctor[] = [
  // ── Hospital Leadership ──
  {
    slug: 'dr-j-sreenivasa-rao',
    name: 'Dr. J. Sreenivasa Rao',
    designation: 'Managing Director & CEO',
    roleBadge: 'Hospital Leadership',
    hospitalName: 'Sreenivasa Multi Speciality Hospital',
    qualifications: 'MD / Healthcare Administration',
    speciality: 'Hospital Leadership & Administration',
    specialitySlug: 'leadership',
    focusAreas: [
      'Hospital Care & Patient Support',
      '15 Speciality Departments',
      'Govt. Recognized Standards',
      'Quality Patient Care',
    ],
    bio: 'Guiding Sreenivasa Multi Speciality Hospital to provide trusted, friendly, and complete medical and surgery care for all families in Anantapur.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. J. Sreenivasa Rao - Managing Director of Sreenivasa Multi Speciality Hospital',
    appointmentLabel: 'Contact Leadership',
    isVerified: true,
    isLeadership: true,
  },

  // ── 1. General Medicine ──
  {
    slug: 'dr-m-roshan-sab',
    name: 'Dr. M. Roshan Sab',
    designation: 'Consultant Physician',
    qualifications: 'M.D., D.A.',
    speciality: 'General Medicine',
    specialitySlug: 'general-medicine',
    opdTimings: 'Mon - Sat: 9:30 AM - 1:30 PM & 5:00 PM - 8:30 PM',
    focusAreas: ['Fever, Cough & Viral Illnesses', 'Diabetes & BP Control', 'Thyroid & Stomach Care', 'Routine Health Checkups'],
    bio: 'Experienced physician providing daily diagnosis and care for fevers, diabetes, high blood pressure, and adult illnesses.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. M. Roshan Sab - General Medicine Physician',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },
  {
    slug: 'dr-g-s-vikram',
    name: 'Dr. G.S. Vikram',
    designation: 'Consultant Physician',
    qualifications: 'M.B. (Gen)',
    speciality: 'General Medicine',
    specialitySlug: 'general-medicine',
    opdTimings: 'Mon - Sat: 10:00 AM - 2:00 PM & 5:30 PM - 9:00 PM',
    focusAreas: ['Adult Checkups & Fever Care', 'Blood Pressure & Diabetes', 'Infection Treatments', 'Preventive Health Care'],
    bio: 'Dedicated physician caring for adult health, seasonal fevers, infections, and long-term health control.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. G.S. Vikram - General Medicine Physician',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 2. Obst & Gynecology ──
  {
    slug: 'dr-p-bharathi',
    name: 'Dr. P. Bharathi',
    designation: 'Consultant Gynaecologist & Obstetrician',
    qualifications: 'M.B.B.S., D.G.O.',
    speciality: 'Obstetrics & Gynaecology (OBG)',
    specialitySlug: 'obstetrics-gynaecology',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:30 PM & 5:30 PM - 8:30 PM',
    focusAreas: ['Pregnancy & Delivery Care', 'Normal & C-Section Deliveries', 'Period Problems & PCOD', 'Women Wellness & Checkups'],
    bio: 'Gentle, experienced women’s health doctor providing pregnancy care, safe deliveries, and treatment for women’s health needs.',
    photo: '/assets/doctors/doctor-obg.png',
    photoAlt: 'Dr. P. Bharathi - Consultant Gynaecologist',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },
  {
    slug: 'dr-g-sireesha',
    name: 'Dr. G. Sireesha',
    designation: 'Consultant Gynaecologist & Obstetrician',
    qualifications: 'M.B.B.S., D.G.O.',
    speciality: 'Obstetrics & Gynaecology (OBG)',
    specialitySlug: 'obstetrics-gynaecology',
    opdTimings: 'Mon - Sat: 10:30 AM - 2:00 PM & 6:00 PM - 8:30 PM',
    focusAreas: ['Antenatal Pregnancy Care', 'Maternal & Newborn Support', 'Hormonal & Period Care', 'Infertility & Wellness Advice'],
    bio: 'Dedicated gynaecologist offering warm and supportive care for mothers and women of all ages.',
    photo: '/assets/doctors/doctor-obg.png',
    photoAlt: 'Dr. G. Sireesha - Consultant Gynaecologist',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 3. Cardiology ──
  {
    slug: 'dr-m-suresh-kumar-reddy',
    name: 'Dr. M. Suresh Kumar Reddy',
    designation: 'Consultant Cardiologist',
    qualifications: 'M.D., D.C.',
    speciality: 'Cardiology (Heart Care)',
    specialitySlug: 'cardiology',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:00 PM & 5:00 PM - 8:00 PM',
    focusAreas: ['Heart Checkups & ECG Review', 'High Blood Pressure & Cholesterol', 'Chest Pain & Breathlessness', 'Heart Health Advice'],
    bio: 'Expert heart specialist caring for chest discomfort, blood pressure, heart rhythm, and preventive cardiac wellness.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. M. Suresh Kumar Reddy - Cardiologist',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 4. Pulmonology ──
  {
    slug: 'dr-p-sudheendra',
    name: 'Dr. P. Sudheendra',
    designation: 'Consultant Pulmonologist (Chest & Lungs)',
    qualifications: 'M.B.B.S., M.D.',
    speciality: 'Pulmonology (Chest & Lungs)',
    specialitySlug: 'pulmonology',
    opdTimings: 'Mon - Sat: 9:30 AM - 1:00 PM & 5:00 PM - 8:00 PM',
    focusAreas: ['Asthma & Allergy Care', 'Chronic Cough & Bronchitis', 'Chest Infections & Wheezing', 'Lung Health & Breathing Tests'],
    bio: 'Specialist chest doctor for breathing difficulty, chronic cough, asthma, allergy, and lung infections.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. P. Sudheendra - Pulmonologist',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },
  {
    slug: 'dr-soujanya-laxmi',
    name: 'Dr. Soujanya Laxmi',
    designation: 'Consultant Pulmonologist',
    qualifications: 'M.D.',
    speciality: 'Pulmonology (Chest & Lungs)',
    specialitySlug: 'pulmonology',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:30 PM & 5:30 PM - 8:00 PM',
    focusAreas: ['Breathing & Lung Disorders', 'Pneumonia & Chest Fever', 'Allergy & Smoker’s Cough', 'Sleep & Breathing Care'],
    bio: 'Experienced chest and lung physician helping patients breathe easy and recover from respiratory problems.',
    photo: '/assets/doctors/doctor-obg.png',
    photoAlt: 'Dr. Soujanya Laxmi - Pulmonologist',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 5. Gastroenterology ──
  {
    slug: 'dr-c-rajneesh-reddy',
    name: 'Dr. C. Rajneesh Reddy',
    designation: 'Consultant Gastroenterologist',
    qualifications: 'M.D., D.M.',
    speciality: 'Gastroenterology (Stomach & Liver)',
    specialitySlug: 'gastroenterology',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:30 PM & 5:30 PM - 8:30 PM',
    focusAreas: ['Acidity, Gas & Indigestion', 'Liver & Jaundice Care', 'Stomach Pain & Ulcers', 'Endoscopy Consultations'],
    bio: 'Specialist stomach and liver doctor treating severe acidity, ulcers, jaundice, liver issues, and digestive problems.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. C. Rajneesh Reddy - Gastroenterologist',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },
  {
    slug: 'dr-govardhan-reddy',
    name: 'Dr. Govardhan Reddy',
    designation: 'Consultant Gastro & Laparoscopic Surgeon',
    qualifications: 'M.S., FRCS',
    speciality: 'Gastroenterology & General Surgery',
    specialitySlug: 'gastroenterology',
    secondarySpecialitySlug: 'general-surgery',
    opdTimings: 'Mon - Sat: 10:30 AM - 2:00 PM & 6:00 PM - 8:30 PM',
    focusAreas: ['Gallbladder & Appendix Surgery', 'Hernia & Intestinal Surgeries', 'Laparoscopic Keyhole Surgeries', 'Piles, Fissure & Fistula Care'],
    bio: 'Highly experienced gastrointestinal and laparoscopic surgeon performing safe, minimally invasive operations.',
    photo: '/assets/doctors/doctor-surgeon.png',
    photoAlt: 'Dr. Govardhan Reddy - Gastro & Laparoscopic Surgeon',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 6. General & Laparoscopic Surgery ──
  {
    slug: 'dr-k-v-madhusudhan',
    name: 'Dr. K.V. Madhusudhan',
    designation: 'Consultant General & Laparoscopic Surgeon',
    qualifications: 'M.S.',
    speciality: 'General & Laparoscopic Surgery',
    specialitySlug: 'general-surgery',
    opdTimings: 'Mon - Sat: 10:00 AM - 2:00 PM & 6:00 PM - 8:30 PM',
    focusAreas: ['Hernia & Appendix Operations', 'Gallbladder Stones Surgery', 'Lumps, Cysts & Abscess Care', 'Wound Repair & Emergency Surgery'],
    bio: 'Skilled general and laparoscopic surgeon providing safe day-care and emergency surgeries with fast recovery.',
    photo: '/assets/doctors/doctor-surgeon.png',
    photoAlt: 'Dr. K.V. Madhusudhan - General Surgeon',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 7. Ortho & Joint Replacement Surgery ──
  {
    slug: 'dr-k-satish',
    name: 'Dr. K. Satish',
    designation: 'Consultant Orthopaedic & Joint Replacement Surgeon',
    qualifications: 'M.S., FRCS, DNB',
    speciality: 'Ortho & Joint Replacement Surgery',
    specialitySlug: 'orthopaedics',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:30 PM & 5:30 PM - 8:30 PM',
    focusAreas: ['Knee & Hip Joint Replacement', 'Fracture & Trauma Surgery', 'Arthritis & Joint Pain Relief', 'Spine & Bone Care'],
    bio: 'Renowned orthopaedic and joint replacement surgeon helping patients regain pain-free walking and movement.',
    photo: '/assets/doctors/doctor-ortho.png',
    photoAlt: 'Dr. K. Satish - Orthopaedic & Joint Replacement Surgeon',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },
  {
    slug: 'dr-srikanth-reddy',
    name: 'Dr. Srikanth Reddy',
    designation: 'Consultant Orthopaedic Surgeon',
    qualifications: 'M.B.B.S., M.S.',
    speciality: 'Ortho & Joint Replacement Surgery',
    specialitySlug: 'orthopaedics',
    opdTimings: 'Mon - Sat: 9:30 AM - 1:00 PM & 5:00 PM - 8:00 PM',
    focusAreas: ['Broken Bones & Fracture Casts', 'Knee, Shoulder & Ankle Pain', 'Ligament & Muscle Sprains', 'Accident & Injury Care'],
    bio: 'Skilled bone and fracture specialist treating injuries, joint stiffness, and musculoskeletal pain.',
    photo: '/assets/doctors/doctor-ortho.png',
    photoAlt: 'Dr. Srikanth Reddy - Orthopaedic Surgeon',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 8. Paediatric Surgery ──
  {
    slug: 'dr-s-hari-prasad',
    name: 'Dr. S. Hari Prasad',
    designation: 'Consultant Paediatric Surgeon',
    qualifications: 'M.B.B.S., M.S., M.Ch',
    speciality: 'Paediatric Surgery (Child Surgery)',
    specialitySlug: 'paediatric-surgery',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:00 PM & 5:30 PM - 8:00 PM',
    focusAreas: ['Newborn & Child Surgeries', 'Child Hernia & Hydrocele', 'Congenital & Birth Condition Surgery', 'Emergency Child Surgery'],
    bio: 'Expert paediatric super-specialist surgeon caring for babies and young children with gentle, precise surgical care.',
    photo: '/assets/doctors/doctor-paediatrician.png',
    photoAlt: 'Dr. S. Hari Prasad - Paediatric Surgeon',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 9. Maxillo Facial Surgery ──
  {
    slug: 'dr-phanidra-guptha',
    name: 'Dr. Phanidra Guptha',
    designation: 'Consultant Maxillofacial Surgeon',
    qualifications: 'BDS, MDS',
    speciality: 'Maxillofacial Surgery (Face & Jaw)',
    specialitySlug: 'maxillofacial-surgery',
    opdTimings: 'Mon - Sat: 10:30 AM - 1:30 PM & 6:00 PM - 8:30 PM',
    focusAreas: ['Face & Jaw Bone Fractures', 'Wisdom Tooth & Jaw Surgeries', 'Facial Pain & Joint Issues', 'Oral & Face Trauma Care'],
    bio: 'Specialist surgeon for facial injuries, jaw fractures, severe dental issues, and corrective jaw surgery.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. Phanidra Guptha - Maxillofacial Surgeon',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },
  {
    slug: 'dr-mahesh-a',
    name: 'Dr. Mahesh A',
    designation: 'Consultant Maxillofacial Surgeon',
    qualifications: 'M.D.S.',
    speciality: 'Maxillofacial Surgery (Face & Jaw)',
    specialitySlug: 'maxillofacial-surgery',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:00 PM & 5:00 PM - 8:00 PM',
    focusAreas: ['Jaw Alignment & Face Trauma', 'Complex Tooth & Jaw Procedures', 'Mouth Cysts & Swellings', 'Facial Reconstruction'],
    bio: 'Experienced surgeon providing skilled treatment for jaw injuries, mouth swellings, and facial reconstruction.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. Mahesh A - Maxillofacial Surgeon',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 10. ENT ──
  {
    slug: 'dr-a-rajesh',
    name: 'Dr. A. Rajesh',
    designation: 'Consultant ENT Specialist & Surgeon',
    qualifications: 'M.S.',
    speciality: 'ENT (Ear, Nose & Throat)',
    specialitySlug: 'ent',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:30 PM & 5:30 PM - 8:30 PM',
    focusAreas: ['Ear Pain & Hearing Checks', 'Sinus, Cold & Blocked Nose', 'Tonsils & Throat Infection', 'Ear Cleaning & Minor Surgery'],
    bio: 'Skilled ENT doctor treating ear discharge, hearing loss, sinus blockages, throat pain, and tonsillitis.',
    photo: '/assets/doctors/doctor-ent.png',
    photoAlt: 'Dr. A. Rajesh - ENT Specialist',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },
  {
    slug: 'dr-b-hari-prasad',
    name: 'Dr. B. Hari Prasad',
    designation: 'Consultant ENT Specialist',
    qualifications: 'M.S.',
    speciality: 'ENT (Ear, Nose & Throat)',
    specialitySlug: 'ent',
    opdTimings: 'Mon - Sat: 10:30 AM - 2:00 PM & 6:00 PM - 8:30 PM',
    focusAreas: ['Nasal Allergy & Polyp Removal', 'Ear Drum & Hearing Problems', 'Voice, Snoring & Throat Care', 'Head & Neck Checkups'],
    bio: 'Experienced ENT specialist offering gentle treatments and endoscopic procedures for ear, nose, and throat ailments.',
    photo: '/assets/doctors/doctor-ent.png',
    photoAlt: 'Dr. B. Hari Prasad - ENT Specialist',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 11. Neuro Physician ──
  {
    slug: 'dr-krishna-kanth',
    name: 'Dr. Krishna Kanth',
    designation: 'Consultant Neuro Physician (Neurologist)',
    qualifications: 'M.D., D.M.',
    speciality: 'Neurology (Neuro Physician)',
    specialitySlug: 'neurology',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:30 PM & 5:30 PM - 8:30 PM',
    focusAreas: ['Headaches & Migraine Care', 'Stroke & Paralysis Treatment', 'Fits & Epilepsy Management', 'Nerve Weakness & Numbness'],
    bio: 'Super-specialist brain and nerve physician treating severe headaches, stroke, seizures, and tingling nerve disorders.',
    photo: '/assets/doctors/doctor-neuro.png',
    photoAlt: 'Dr. Krishna Kanth - Neuro Physician',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },
  {
    slug: 'dr-m-venkataramana',
    name: 'Dr. M. Venkataramana',
    designation: 'Consultant Neuro Physician (Neurologist)',
    qualifications: 'M.D., D.M.',
    speciality: 'Neurology (Neuro Physician)',
    specialitySlug: 'neurology',
    opdTimings: 'Mon - Sat: 10:30 AM - 2:00 PM & 6:00 PM - 8:30 PM',
    focusAreas: ['Brain & Nerve Disorders', 'Dizziness & Memory Problems', 'Parkinson’s & Tremors', 'Neuropathy & Spine Nerve Care'],
    bio: 'Experienced neurologist providing compassionate clinical care for brain, spine, and nerve disorders.',
    photo: '/assets/doctors/doctor-neuro.png',
    photoAlt: 'Dr. M. Venkataramana - Neuro Physician',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 12. Plastic Surgery ──
  {
    slug: 'dr-p-rajakullayyappa',
    name: 'Dr. P. Rajakullayyappa',
    designation: 'Consultant Plastic & Reconstructive Surgeon',
    qualifications: 'M.S., M.Ch',
    speciality: 'Plastic Surgery',
    specialitySlug: 'plastic-surgery',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:00 PM & 5:00 PM - 8:00 PM',
    focusAreas: ['Burn Wound & Scar Care', 'Skin Grafting & Trauma Repair', 'Hand Injury & Tendon Surgery', 'Cosmetic & Reconstructive Surgery'],
    bio: 'Super-specialist plastic surgeon restoring skin, wounds, burns, hand injuries, and cosmetic concerns.',
    photo: '/assets/doctors/doctor-surgeon.png',
    photoAlt: 'Dr. P. Rajakullayyappa - Plastic Surgeon',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 13. Anaesthesia & Intensive Care ──
  {
    slug: 'dr-g-naveen-kumar',
    name: 'Dr. G. Naveen Kumar',
    designation: 'Consultant Anaesthesiologist & Critical Care',
    qualifications: 'M.B.B.S., D.A.',
    speciality: 'Anaesthesia & Intensive Care',
    specialitySlug: 'anaesthesia-icu',
    opdTimings: '24/7 Surgical & ICU Support',
    focusAreas: ['Safe Surgical Anaesthesia', 'ICU & Critical Patient Care', 'Pain Management After Surgery', 'Emergency Resuscitation'],
    bio: 'Specialist anaesthetist ensuring complete safety, comfort, and pain-free experience during surgeries and ICU care.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. G. Naveen Kumar - Anaesthesiologist',
    appointmentLabel: 'Contact Desk',
    isVerified: true,
  },
  {
    slug: 'dr-m-vinay',
    name: 'Dr. M. Vinay',
    designation: 'Consultant Anaesthesiologist & ICU Specialist',
    qualifications: 'M.B.B.S., D.A.',
    speciality: 'Anaesthesia & Intensive Care',
    specialitySlug: 'anaesthesia-icu',
    opdTimings: '24/7 Surgical & ICU Support',
    focusAreas: ['Pre-Surgery Checkups', 'Intensive Care Unit (ICU)', 'Emergency Airway & Life Support', 'Patient Monitoring & Safety'],
    bio: 'Experienced critical care and anaesthesia specialist dedicated to continuous patient safety in surgery and recovery.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. M. Vinay - Anaesthesiologist',
    appointmentLabel: 'Contact Desk',
    isVerified: true,
  },

  // ── 14. Urology ──
  {
    slug: 'dr-y-harinath-reddy',
    name: 'Dr. Y. Harinath Reddy',
    designation: 'Consultant Urologist & Andrologist',
    qualifications: 'M.S., M.Ch',
    speciality: 'Urology (Kidney & Urine Care)',
    specialitySlug: 'urology',
    opdTimings: 'Mon - Sat: 10:00 AM - 1:30 PM & 5:30 PM - 8:30 PM',
    focusAreas: ['Kidney Stones & Laser Removal', 'Prostate & Urine Blockages', 'Urinary Infections & Burning', 'Men’s Health & Kidney Care'],
    bio: 'Super-specialist urologist offering modern laser treatments for kidney stones, prostate issues, and urinary tract health.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. Y. Harinath Reddy - Urologist',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },
  {
    slug: 'dr-p-satish-kumar',
    name: 'Dr. P. Satish Kumar',
    designation: 'Consultant Urologist',
    qualifications: 'M.S., DNB',
    speciality: 'Urology (Kidney & Urine Care)',
    specialitySlug: 'urology',
    opdTimings: 'Mon - Sat: 10:30 AM - 2:00 PM & 6:00 PM - 8:30 PM',
    focusAreas: ['Kidney & Bladder Stones', 'Urine Flow Problems & Strictures', 'Urology Surgery & Laser Care', 'Kidney Health Checkups'],
    bio: 'Skilled urology specialist caring for kidney stones, bladder health, and urinary conditions.',
    photo: '/assets/doctors/doctor-specialist.png',
    photoAlt: 'Dr. P. Satish Kumar - Urologist',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },

  // ── 15. Neuro Surgery ──
  {
    slug: 'neurosurgery-specialist',
    name: 'Consultant Neurosurgeon',
    designation: 'Department of Neurosurgery',
    qualifications: 'Brain & Spine Surgical Care',
    speciality: 'Neurosurgery (Brain & Spine)',
    specialitySlug: 'neurosurgery',
    opdTimings: 'By Prior Appointment / OPD Slots',
    focusAreas: ['Head Injury & Emergency Care', 'Spine & Neck Pain Relief', 'Nerve Compression Relief', 'Brain & Spine Surgeries'],
    bio: 'Specialist surgical doctor for head injury, spine disc problems, severe neck/back pain, and nerve surgeries.',
    photo: '/assets/doctors/doctor-neuro.png',
    photoAlt: 'Consultant Neurosurgeon at Sreenivasa Hospital',
    appointmentLabel: 'Book Consultation',
    isVerified: true,
  },
];

export function getDoctorBySlug(slug: string): Doctor | undefined {
  return doctors.find((d) => d.slug === slug);
}
